In [ ]:
# data analysis stack
import numpy as np
import pandas as pd

# data visualization stack
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style('whitegrid')

# miscellaneous
import warnings
warnings.filterwarnings("ignore")
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

# deep learning stack
import tensorflow as tf
from tensorflow import keras
#from tensorflow.keras import Model
from tensorflow.keras.preprocessing import image

#### Load pretrained model

In [2]:
import os
CLASSES = os.listdir('./data/Trainimages')
CLASSES

['Shoes', 'Spoons', 'Books', 'Forks']

In [3]:
# define an image data generator
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
data_gen = keras.preprocessing.image.ImageDataGenerator(preprocessing_function=preprocess_input)

# a generator that returns batches of x and y arrays
test_data_gen = data_gen.flow_from_directory(
        directory='./data/Testimages//',
        class_mode="categorical",
        classes=CLASSES,
        target_size=(224, 224)
)

Found 39 images belonging to 4 classes.


In [4]:
# load in all images at once
xtest, ytest = next(test_data_gen)
xtest.shape, ytest.shape

((32, 224, 224, 3), (32, 4))

In [ ]:
def transfer_learning_prediction(model,x,y):
    """
    This function returns a dataframe with class probabilities
    along with true class label 
    """
    # convert vectorized classes into strings
    y = [''.join([i*j for (i,j) in zip(CLASSES,vector)]) for vector in y.astype(int)]
    # prediction dataframe along with true class
    prediction_df = pd.DataFrame(
        columns=CLASSES,
        data=np.round(model.predict(x,verbose=0),3)
    )
    prediction_df['class'] = y
    return prediction_df

In [5]:
from tensorflow import keras
model = keras.models.load_model('my_model.h5')


In [7]:
pred=model.predict(xtest)

1/1 [==============================] - 1s 1s/step


In [8]:
print(pred)

[[9.9999225e-01 5.6890281e-06 1.5013621e-06 4.5176671e-07]
 [3.6771577e-03 6.4630392e-03 7.7504271e-01 2.1481715e-01]
 [9.9998677e-01 6.0476527e-06 7.1852996e-06 6.2443696e-08]
 [1.8904531e-04 2.5524662e-04 9.8016709e-01 1.9388592e-02]
 [5.6362613e-05 9.4115370e-05 9.9954164e-01 3.0791687e-04]
 [1.3483737e-09 4.9252209e-04 2.4788471e-09 9.9950743e-01]
 [9.9989963e-01 5.1493935e-05 3.9833689e-05 9.0602962e-06]
 [1.2201895e-10 9.9998903e-01 1.2205493e-08 1.0910879e-05]
 [9.9672616e-01 3.1983552e-03 4.9511495e-05 2.5869989e-05]
 [2.7904434e-05 5.9980625e-01 8.0160771e-06 4.0015790e-01]
 [7.0552790e-04 7.8328165e-05 1.6835564e-01 8.3086056e-01]
 [2.1138375e-07 9.9964356e-01 4.6818236e-08 3.5624712e-04]
 [9.9958009e-01 7.3122465e-05 2.9248762e-04 5.4208842e-05]
 [1.4858458e-08 1.8446376e-07 2.5907812e-11 9.9999976e-01]
 [2.3149778e-03 8.1350678e-01 1.4801705e-02 1.6937660e-01]
 [3.4865441e-10 9.9999750e-01 3.6041292e-09 2.5336815e-06]
 [5.4566594e-06 9.9959904e-01 5.7685634e-07 3.9486185e-0

In [25]:
ind=np.argmax(pred[0])

In [26]:
CLASSES[ind]

'Shoes'

In [21]:
np.argmax(np.array(pred), axis=1)

array([0, 2, 0, 2, 2, 3, 0, 1, 0, 1, 3, 1, 0, 3, 1, 1, 1, 0, 3, 1, 2, 3,
       2, 3, 0, 1, 3, 3, 2, 2, 1, 1])